name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci

      - name: Buildar projeto
        run: npm run build

      - name: Deploy para GitHub Pages repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: MRaphaelpy/mraphaelpy.github.io
          publish_branch: main
          publish_dir: ./dist
          commit_message: "Deploy automático do portfólio"
